package com.allhome.colourcoats.chat;

/**
 * The JSON the model must return every turn (schema generated by BeanOutputConverter).
 * Only {@code reply} is shown to the visitor; the rest is internal sales data.
 */
public record ModelAnswer(String reply, boolean handoff, String handoffReason,
                          String persona, String intent, LeadDetails lead) {

    /** Details stated by the visitor anywhere in the conversation; null when not known. */
    public record LeadDetails(String name, String phone, String email, String city, String projectType,
                              String spaces, String finishInterest, String areaSize, String timeline,
                              String budget, String callbackTime) {}
}
